Chore(deps): Bump org.projectlombok:lombok from 1.18.30 to 1.18.42
Bumps org.projectlombok:lombok from 1.18.30 to 1.18.42.
## Changelog

Sourced from org.projectlombok:lombok's changelog.

v1.18.42 (September 18th, 2025)

FEATURE: All the various @Log annotations now allow you to change their access level (they still default to private). #2280. Thanks to new contributor Liam Pace!
BUGFIX: Javadoc parsing was broken in Netbeans and ErrorProne for JDK25 #3940.

v1.18.40 (September 4th, 2025)

PLATFORM: JDK25 support added #3859.
BUGFIX: Recent versions of eclipse (or the eclipse-based java lang server for VSCode) caused java.lang.IllegalArgumentException: Document does not match the AST. Issue #3886.
PERFORMANCE: @ExtensionMethod is now significantly faster Issue #3866.
BUGFIX: the command line config tool would emit incorrect output for nullity annotations. Issue #3931.
FEATURE: @Jacksonized @Accessors(fluent=true) automatically creates the relevant annotations such that Jackson correctly identifies fluent accessors. Issue #3265, Issue #3270.
IMPROBABLE BREAKING CHANGE: From versions 1.18.16 to 1.18.38, lombok automatically copies certain Jackson annotations (e.g., @JsonProperty) from fields to the corresponding accessors (getters/setters). However, it turned out to be harmful in certain situations. Thus, Lombok does not automatically copy those annotations any more. You can restore the old behavior using the config key lombok.copyJacksonAnnotationsToAccessors = true.

v1.18.38 (March 31st, 2025)

PLATFORM: JDK24 support added.
FEATURE: Lombok's nullity annotation now supports JSpecify out of the box, using config key jspecify.

BUGFIX: Recent eclipse releases would get you 'negative length' error. The bug had always been in lombok but didn't matter until recent releases. Issue #3823.
BUGFIX: The 'extract local variable' refactor script of VSCode wouldn't replace all occurrences if run on a method call to a lombok generated method. Issue #3783.

v1.18.36 (November 15th, 2024)

PLATFORM: JDK23 support added.
BUGFIX: Eclipse projects using the com.pro-crafting.tools:jasperreports-maven-plugin will now compile.

v1.18.34 (June 28th, 2024)

PLATFORM: Added support for Eclipse 2024-06; you'd get some NoSuchMethodError traces in your logs if using @Builder or @Singular prior to this fix. Issue #3638.
IMPROBABLE BREAKING CHANGE: Lombok now adds @lombok.Generated by default to methods and types it generates. This may result in accidentally increasing your test coverage percentage. Issue #3667.
IMPROBABLE BREAKING CHANGE: When lombok.config contains lombok.onX.flagUsage = WARNING, from now on warnings will actually be generated if onX is used.Issue #2848
BUGFIX: When @SuperBuilder was used on a type with an generic array type, it would error wrong number of type arguments. Issue #3694.
FEATURE: Lombok generates javadoc for you for most of the methods it adds; with this release, javadoc is also added to generated constructors. Issue #933.

v1.18.32 (March 20th, 2024)

PLATFORM: Initial JDK22 support added.
PLAFTORM Added support for Eclipse 2024-03. Issue #3620.
PLATFORM: Added support for recent versions of eclipse (released Q4 2023 or later or so) which would cause failures in the eclipse logs such as java.lang.NoSuchMethodError: 'java.lang.StringBuffer org.eclipse.jdt…. Issue #3564.
FEATURE: @Locked has been introduced. Like @Synchronized but with java.util.concurrent.locks locks instead of the synchronized primitive. Thanks, Pim van der Loos for the PR! Issue #3506.
NECROMANCY: Inlining a generated getter in eclipse would result in eclipse incorrectly replacing calls with @Getter instead of the actual field's name. Issue #562. This issue is almost old enough to drink. Points for dedication go to Rawi for fixing this one.
BUGFIX: When @SuperBuilder was used on a type with an annotated generic type, it would error wrong number of type arguments. Issue #3592.
BUGFIX: It was possible to create an infinite build loop using @ExtensionMethod. Issue #3225.
BUGFIX: Using @Getter(lazy=true) would fail if the expression contained a variable called value. Issue #2917.
BUGFIX: Many lombok features wouldn't work properly on records contained within an outer type unless you explicitly marked it static. Issue #3497 Issue #3559.

BUGFIX: Eclipse projects using the com.pro-crafting.tools:jasperreports-plugin will now compile.
BUGFIX: @FieldNameConstants now works when generated fields are involved. Issue #3529.
IMPROBABLE BREAKING CHANGE: For JSpecify, the package name changed from org.jspecify.nullness to org.jspecify.annotations, which might lead to a different null analysis. Issue #3608.

## Commits

2031eb0 [release] pre-release version bump for v1.18.42
c95a6c1 Merge branch 'logger-access'
71d85ca #2280 Add delivery of this 'access for logging' to the changelog.
99ba3e3 [trivial] Slightly reworded the javadoc on each @Log annotation's `access()
e9cf11e [trivial][style]
a6d5568 [deprecation] Marked AccessLevel.MODULE as deprecated. It was written for a
492011d Refactored to use Javac/Eclipse utility function
c1f7f66 Update copyright in logger files
f63f40a Add myself to AUTHORS
9152c34 Fix failing tests
Additional commits viewable in compare view

![Dependabot compatibility score](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

You can trigger a rebase of this PR by commenting `@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

Change-Id: I023e43d7376878de097c1120c58b246b8efedac0

---

## Dependabot commands and options

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating it. You can achieve the same result by closing it manually
- `@dependabot show  ignore conditions` will show all of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop Dependabot creating any more for this major version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop Dependabot creating any more for this minor version (unless you reopen the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop Dependabot creating any more for this dependency (unless you reopen the PR or upgrade to it yourself)

> **Note**
> Automatic rebases have been disabled on this pull request as it has been open for over 30 days.

Issue-ID: CIMAN-666
Signed-off-by: dependabot[bot] <support@github.com>
Signed-off-by: lfit.gh2gerrit <releng+lfit-gh2gerrit@linuxfoundation.org>
Change-Id: Ib42d0085317cb50dcfcf08a48b7292b28e87f725
GitHub-PR: https://github.com/lfit/sandbox/pull/2
GitHub-Hash: 45ac6af37ab4837f